### ISSUE TITLE
HTTPS redirect loop

### ISSUE THREAD

**Issue by bryanlarsen** [bitnami/bitnami-docker-magento#64] opened 2017-04-28 17:09 UTC
**Description**

We get a redirect loop when accessing the admin page.  It redirects us to an HTTP url, which is redirected to an HTTPS url by our ingress server, which then is redirected to an HTTP url by magento, ad infinitum.

Note that this is a bug report against the Kubernetes Helm chart for magento.   I believe that this is a better location for the issue than kubernetes/charts.   However, if you wish I can open the issue there instead.

**Steps to reproduce the issue:**

1. Install on metal via install instructions on https://github.com/kubernetes/charts/pull/958.   `magentoHost: magento-test.clara.io`
2. Add Kubernetes Ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: magento-test-ingress
spec:
  tls:
  - secretName: tls-clara-io
    hosts: 
      - magento-test.clara.io
  rules:
  - host: magento-test.clara.io
    http:
      paths:
      - path: /
        backend:
          serviceName: magento-test-magento
          servicePort: 80
```

3. try to access https://magento-test.clara.io/admin or http://magento-test.clara.io/

**Describe the results you received:**

redirect loop error from browser

https://magento-test.clara.io/admin 302 -> http://magento-test.clara.io/index.php/admin/admin/index/index/key/3d40c6fcfe062a7006670872a2ecd5757af6019495cc23bca93caed8b24a69f5/

http://magento-test.clara.io/index.php/admin/admin/index/index/key/3d40c6fcfe062a7006670872a2ecd5757af6019495cc23bca93caed8b24a69f5/ 301 -> https://magento-test.clara.io/index.php/admin/admin/index/index/key/3d40c6fcfe062a7006670872a2ecd5757af6019495cc23bca93caed8b24a69f5/

http://magento-test.clara.io/index.php/admin/admin/index/index/key/3d40c6fcfe062a7006670872a2ecd5757af6019495cc23bca93caed8b24a69f5/ 302 -> http://magento-test.clara.io/index.php/admin/admin/index/index/key/8384346757cb2e6b2cddf7e50cb1d6c8016ba0c15d4a85baf3033aa3a757486d/

**Describe the results you expected:**

display admin page

**Version**

- Output of `docker version`:

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

ingress version: gcr.io/google_containers/nginx-ingress-controller:0.8.3

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

physical

**Comment by chipironcin** [comment] 2017-05-04 08:56
Hi @bryanlarsen 
It seems an issue with the Magento application rather than the Helm chart itself.
I have found an answer that may solve your issue:
https://magento.stackexchange.com/a/38251

>Add these lines to the end of your .htaccess and it should be fine:

    # Detect the Load-Balancer-Header and set the header magento expects
    SetEnvIf X-Forwarded-Proto https HTTPS=on

Could you try it?
Regards,
Jorge

**Comment by bryanlarsen** [comment] 2017-05-04 16:41
I tried it, it doesn't work.

**Comment by javsalgar** [comment] 2017-05-09 15:10
Hi, 

Thanks for reporting. We are looking into the issue. It seems the cause is that SSL termination must occur in Ingress. However, it is Apache that it is doing the SSL termination, and hence the loop.

**Comment by bryanlarsen** [comment] 2017-05-09 15:20
Thanks, there's definitely more going on than I understand, @chipironcin's suggestion should have worked.   I also tried telling ingress to use SSL to connect to magento (https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md#secure-backends) and that didn't work either, although that certainly could have been PBKAC.   I didn't notice ssl_passthrough, perhaps that would have worked.

**Comment by sameersbn** [comment] 2017-08-02 07:04
I am seeing a similar issue while using the default docker-compose.yml file. When I try to access https://localhost/admin, i am redirected to http://localhost/admin and I am not able to login.

**Comment by arapulido** [comment] 2017-09-21 11:11
@prydonius Can you have a look to this one, please?

**Comment by carrodher** [comment] 2017-09-22 09:52
Hi @bryanlarsen, can you take a look at my answer to this related issue #68?

It seems that it is due to the Magento configuration, in the mentioned issue, I am proposing a way to configure it properly using the web interface. If the issue is solved using this approach, we will study the viability to include this option enabled by default.

**Comment by amirhmoradi** [comment] 2017-11-09 07:04
Hi,
I had the same issue, and here is how I solved it:
NB: As you can't access the magento admin, you should do the modification directly in the database.

1: Find the database name (and host if needed) in magento's env.php file.
2: Get into the database (either via cli or some tool (ex: phpmyadmin))
3: Update the `core_config_data` table to make sure magento uses the secure urls in frontend and backend:
`UPDATE core_config_data SET value=1 WHERE  path IN ('web/secure/use_in_frontend','web/secure/use_in_adminhtml');`

After doing that, the magento admin worked!

Fyi: I am using the following config:
(NB: This is a DYI garage hobby setup :D )

Internet <--> pfSense Firewall <--> HAProxy <-->  Kubernetes <--> Traefik with Let's Encrypt SSL termination <--> Magento 2.2 Ingress <--> Magento Deployment

Some more details for nerds:
pfSense acts as firewall
HAProxy load balances traffic on Kubernetes workers and on multiple Kubernetes deployments
Using Traefik Helm Chart with Let's Encrypt SSL
Magento Ingress is written by myself,
Using Magento Helm Chart (mod to use latest mariadb)
Using MariaDB Helm Chart
Using latest Redis and Memcached Helm Charts
Using Ceph as Storage
All on 10 VMs running on latest MAAS (maas.io) and managed via latest Ubuntu Juju
VMs are running on ESXi 6.5, on a dedicated server.

Have fun !

**Comment by prydonius** [comment] 2017-12-21 15:09
thanks for sharing this @amirhmoradi. @carrodher should we document this or is there a way we could fix this on startup?

**Comment by chipironcin** [comment] 2017-12-27 12:43
@prydonius yes
Opened an internal task for fixing this. Thanks everyone

**Comment by sabbour** [comment] 2018-01-24 01:29
Any updates on this?

**Comment by tompizmor** [comment] 2018-01-26 15:35
Hello @sabbour,

We recently released Magento 2.2.2-r2 including a change in the apache configuration that allows deploying Magento behind an ingress server using the right protocols and avoiding application misconfiguration. 
By setting `
SetEnvIf X-Forwarded-Proto "https" HTTPS=on` in the apache configuration we let apache know we're behind an SSL reverse proxy.

However, the redirection loop will still happen as by default Magento is configured with insecure admin. In order to fix it, you will need to follow @amirhmoradi instructions (https://github.com/bitnami/bitnami-docker-magento/issues/64#issuecomment-343065461)

**Comment by ianblenke** [comment] 2018-02-08 16:20
After a long debug session, even with @amirhmoradi's instructions, I was having problems with the redirect loop.

The solution was to insert a missing `core_config_data` row for the path `web/cookie/cookie_domain` with a value of the fully qualified DNS name of my magento website URL.

First, try updating any existing row. You only want one row:

```
update core_config_data set value = 'magento.example.com' where path = 'web/cookie/cookie_domain';
```

If the result says `Rows matched: 0  Changed: 0  Warnings: 0`, you don't have that row in your `core_config_data` table yet.

Here is the SQL insert that I used to add it:

```
insert into core_config_data (scope, scope_id, path, value) VALUES ('default', 0, 'web/cookie/cookie_domain', 'magento.example.com');
```

After adding that, I was able to reach the `/admin` URL.

I hope this helps someone.

**Comment by tompizmor** [comment] 2018-02-09 11:26
Thanks @ianblenke!  I'm sure this is helpful.

**Comment by FireLizard** [comment] 2018-04-11 16:15
Hello @tompizmor ,

I'm not able to get into the backend area :(
I've configured magenta as proposed by @amirhmoradi and @ianblenke but nothing worked for me.

#### My configuration

docker-compose.yml
```yml
services:
    magento:
        environment:
            MAGENTO_HOST: 'magento.localhost'
```

core_config_data (database table)

path | value
---- | -----
web/unsecure/base_url | http://magento.localhost/
web/secure/base_url | https://magento.localhost/
web/cookie/cookie_domain | magento.localhost

**Comment by tompizmor** [comment] 2018-04-12 14:07
Hello @FireLizard ,

Can you please tell us a bit more about your deployment? 
Are you just running `docker-compose up` with the default docker-compose from the repository? In that case, you should be able to access via HTTP by default to the admin panel. 

And to enable HTTPS you could follow the steps at https://github.com/bitnami/bitnami-docker-magento/issues/68#issuecomment-331402796 (As long as you are able to login via HTTP in the admin panel)

**Comment by FireLizard** [comment] 2018-04-12 18:40
Thank you for your reply, @tompizmor .

I'm running 
```bash
git clone --depth=1 https://github.com/bitnami/bitnami-docker-magento.git
cd bitnami-docker-magento 
docker-compose up
```

At the very first time I could access `http://127.0.0.1/admin`. It showed me a login form.
But when I headed over to `https://127.0.0.1/admin` (SSL) I've got into the redirection loop.
Back to `http://127.0.0.1/admin` I could not login anymore, because there was also the redirection loop then.

**I had to delete the cookies of my browser.**
Now it works as expected!

**Comment by javsalgar** [comment] 2018-04-13 07:55
So, from what I see, it was only a matter of cleaning the cookies, could you confirm that?

**Comment by FireLizard** [comment] 2018-04-13 12:15
Yes, that is right @javsalgar .

I don't no why, but that solved my problem.

**Comment by javsalgar** [comment] 2018-04-16 07:52
Great. Sometimes browser can be a bit cumbersome, especially when dealing with containers and addresses like 127.0.0.1. If you find other issues please let us know :)

**Comment by G1itcher** [comment] 2018-04-24 11:05
@amirhmoradi and @ianblenke are heroes and their names should be shouted from the hill tops. Fixed my issue, many thanks.

**Comment by G1itcher** [comment] 2018-04-26 09:11
Eugh, redeployed to another location and reapplied the above fixes and it hasn't resolved the looping redirect. At a loss now

**Comment by amirhmoradi** [comment] 2018-04-26 21:19
@G1itcher did you try doing a cache:clean and a cache:flush via magento cli afterwards?
Sometimes, the issue might also arise from your browser caching the http/s route=> try opening the admin via Incognito Mode.

**Comment by G1itcher** [comment] 2018-04-27 06:11
@amirhmoradi I ended up going in and removing the cache manually and that seemed to resolve it. I'm quickly learning that Magento is a fiddly beast! Many thanks for getting back to me; genuinely appreciated

**Comment by jamesprocook** [comment] 2018-06-12 12:09
I was also having this problem after copying the docker-compse.yml section for 'mouting directories as data volumes with docker composer'

If you add     - MAGENTO_HOST=magento.localhost as an environment variable for the magento container it will fix the problem

[docker-compose-fix-redirect.txt](https://github.com/bitnami/bitnami-docker-magento/files/2093917/docker-compose-fix-redirect.txt)

**Comment by lcapriotti** [comment] 2018-11-15 08:52
Would it be possible to have an environmental variable controlling /web/secure/use_in_adminhtml ?
That value keeps on being reset to 0 once the container restarts.

**Comment by javsalgar** [comment] 2018-11-19 07:33
Hi,

Thanks for the suggestion, we will evaluate and consider it for future container releases. I will update this thread once this feature is available.

**Comment by mysil2** [comment] 2018-11-19 08:43
Well, there could also be other variables that is convenient to override. Every time I'm reinstalling with a database backup I have to change locale, timezone and currency. Also media and static url if you have a CDN.

**Comment by javsalgar** [comment] 2018-11-20 07:48
Thanks for the feedback! :)

**Comment by cmeyertons** [comment] 2018-11-29 12:16
# Full workaround fix 
(consolidated from @amirhmoradi  and @ianblenke - **you guys rock**)

## MySql script:

```mysql
SET @domain = 'magento.example.com';

UPDATE core_config_data SET value = 1 WHERE path IN ('web/secure/use_in_frontend','web/secure/use_in_adminhtml') and value = 0;

INSERT INTO core_config_data (scope, scope_id, path, value)
VALUES ('default', 0, 'web/cookie/cookie_domain', @domain)
ON DUPLICATE KEY UPDATE
  value = @domain;

select * from core_config_data WHERE path IN ('web/secure/use_in_frontend','web/secure/use_in_adminhtml', 'web/cookie/cookie_domain');
```

## Flush cache
```
docker exec CONTAINER_ID -it "php /opt/bitnami/magento/htdocs/bin/magento cache:flush"
# I had a problem w/ file permissions after this point
docker exec CONTAINER_ID -it "sudo chmode -R 777 /opt/bitnami/magento/htdocs/generated/*"
```

**Comment by tompizmor** [comment] 2018-11-30 09:00
Thanks for the summary @cmeyertons!

**Comment by Nolaan** [comment] 2018-12-05 15:10
@cmeyertons The Flush Cache part of your solution is yielding error on my side.
Here's the syntax I used : 
```
docker exec -it bitnamimagento2_magento_1 php /opt/bitnami/magento/htdocs/bin/magento cache:flush
docker exec -it bitnamimagento2_magento_1 sudo chmod -R 777 /opt/bitnami/magento/htdocs/generated/
```

**Comment by tompizmor** [comment] 2018-12-12 16:35
Can you share the error message?

**Comment by carylewis** [comment] 2018-12-23 14:36
The following steps worked for me, running the default settings. Magento is accessible via https://127.0.0.1

docker exec ...magento_1 bash (the ... contain my machine name)

Obtain the mysql access information from:

/bitnami/magento/htdocs/app/etc/env.php

(the following worked on my docker container, using the default values)

mysql -hmariadb --port 3306 -ubn_magento -pmagento_db_password bitnami_magento

execute:

UPDATE core_config_data SET value = 1 WHERE path IN ('web/secure/use_in_frontend','web/secure/use_in_adminhtml') and value = 0;

exit from mysql client

flush the magento cache:

 php /opt/bitnami/magento/htdocs/bin/magento cache:flush

I hope this helps.

Really the mysql step should be added to the docker compose file.

**Comment by katmai** [comment] 2019-07-17 08:24
is there any way to get a flag for setting that use_in_adminhtml to enabled in docker compose? would be great instead of having to do workarounds for something so trivial

**Comment by javsalgar** [comment] 2019-07-17 08:46
We were considering allowing initialization scripts in the container, just like we have with our infrastructure containers. We do not have an ETA for this but we will update the ticket when we work on it.

**Comment by VDuda** [comment] 2019-09-28 15:45
Ok after doing all the suggested and banging my head against this the past 2 days. Because it should be pretty solvable. I still can't access the admin and get the constant 302 redirects. I'm not sure what else to do. 

![image](https://user-images.githubusercontent.com/6300279/65818841-94b18b00-e1e3-11e9-807a-41eb1b00fc06.png)

I have the following setup in k8s. 

K8S LB (80, 443) <-> ingress controller (80,443) <-> ClusterIP (80) <-> Magento (80)

I do the SSL termination via LE and redirect the traffic to port 80. 

I followed all the suggestions and have the following in my DB. 
![image](https://user-images.githubusercontent.com/6300279/65818957-aba4ad00-e1e4-11e9-93b1-01ce49e37453.png)

I cleared my cache via the `php cache:clear` & `cache:flush`. I did notice my container crashes on the flush for some reason. Also another interesting point, when I look inside the /var/cache directory even after running the cache:flush I still have objects in there. When I clear them via `rm -rf ./*` the container halts and then I notice in the logs that apache reboots. And on reboot I see the same cache in the `var/cache`

I also opened my own issue to address this here, #118

**Comment by VDuda** [comment] 2019-10-01 02:18
Ugh this is beyond frustrating, I've spent maybe 4 days hammering on this issue and only now resolving it. For anyone facing this issue, when they add a domain (because it seems to appear when you associate your server with a domain name). 

You should do the following:
```
<path-to-mage-htdocs>/bin/magento-cli config:set web/url/redirect_to_base 0
<path-to-mage-htdocs>/bin/magento-cli cache:clean
<path-to-mage-htdocs>/bin/magento-cli cache:flush
```

I started to notice that the URL in the redirect loop included the www prefix, and went after tackling which variables redirected. I was facing this issue in the latest release, 2.3.X

**Comment by javsalgar** [comment] 2019-10-01 06:14
Hi,

Thank you very much for sharing this. I'm sure it will be useful for the community :) I will update this ticket when we have more news about allowing custom init scripts.

**Comment by michalmikolajczyk** [comment] 2019-11-14 09:54
This Issue is not solved. I followed the instructions, have the correct values in db persistent and a very similar setup to @VDuda but it still does not work.

**Comment by andresbono** [comment] 2019-11-15 13:17
Thanks for reporting the issue, @michalmikolajczyk. Let's continue the conversation on #123 where you have shared some info.

**Comment by marcosbc** [comment] 2021-01-20 19:02
Hi all, we have just released a new major release of the Bitnami Docker image for Magento, [2.4.1-debian-10-r80](https://github.com/bitnami/bitnami-docker-magento#241-debian-10-r80). It includes major changes with respect to how the image is initialized, and now the source code for the initialization scripts is also published in the [rootfs](https://github.com/bitnami/bitnami-docker-magento/tree/master/2/debian-10/rootfs) folder of this repo.

It also includes any options to enable HTTPS such as `MAGENTO_ENABLE_HTTPS` and `MAGENTO_ENABLE_ADMIN_HTTPS` which should allow you to solve the issues above. Therefore I'm closing this issue, but please do not hesitate to let us know if you continue finding issues.

**Closed by marcosbc** 2021-01-20 19:02 UTC
Labels: on-hold
