### ISSUE TITLE
installed magento the helm chart successful , but can't reach the login page

### ISSUE THREAD

**Issue by luna1230** [bitnami/bitnami-docker-magento#120] opened 2019-10-22 08:46 UTC
I try to install the helm chart in azure aks using the following command
helm install --name magento2 --set magentoUsername=admin,magentoPassword=password,mariadb.mariadbRootPassword=secretpassword,elasticsearch.sysctlImage.enabled=true azure-marketplace/magento
helm upgrade magento2 azure-marketplace/magento --set magentoHost=137.135.78.64,magentoPassword=password,mariadb.mariadbRootPassword=VnnwmC7aKP,mariadb.db.password=iL0rNyw646
now all pods is running and I could login the admin portal . but when click "login" or "create account" in Home Page http://137.135.78.64
url turn to https://137.135.78.64/index.php/customer/account/login/referer/aHR0cDovLzEzNy4xMzUuNzguNjQvaW5kZXgucGhwLw%2C%2C/
and show can’t reach this page

**Comment by marcosbc** [comment] 2019-10-24 16:05
Hi, I'm closing this issue as a duplicate of https://github.com/bitnami/charts/issues/1508. Let's continue there. Thanks!

**Closed by marcosbc** 2019-10-24 16:05 UTC
