### ISSUE TITLE
Arm64 Support for M1 and other Arm processors.

### ISSUE THREAD

**Issue by dbteku** [bitnami/bitnami-docker-magento#233] opened 2022-02-16 20:52 UTC
### Name and Version

bitnami/magento

### What is the problem this feature will solve?

M1 Mac/ Arm Support

### What is the feature you are proposing to solve the problem?

Building/exporting a docker that is arm64 compatible. This will allow M1 macs and arm processors to handle magento running.

### What alternatives have you considered?

Rebuilding your entire tree from scratch.

**Comment by juan131** [comment] 2022-02-17 07:16
Duplicate of https://github.com/bitnami/charts/issues/7305

**Closed by juan131** 2022-02-17 07:16 UTC
