### ISSUE TITLE
How to increase PHP memory_limit?

### ISSUE THREAD

**Issue by crfroehlich** [bitnami/bitnami-docker-magento#114] opened 2019-08-12 15:43 UTC
**Description**

Per #89, if I try to execute `php /opt/bitnami/magento/htdocs/bin/magento sampledata:deploy`

I get this output:
```
<warning>Do not run Composer as root/super user! See https://getcomposer.org/root for details</warning>
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 37748736 bytes) in /opt/bitnami/magento/htdocs/vendor/composer/composer/src/Composer/DependencyResolver/RuleSet.php on line 90

Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 37748736 bytes) in /opt/bitnami/magento/htdocs/vendor/composer/composer/src/Composer/DependencyResolver/RuleSet.php on line 90

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.#
```

**Steps to reproduce the issue:**

1. Follow the installation steps for creating a fresh set of containers
2. Open exec on the magento container
3. `Run php /opt/bitnami/magento/htdocs/bin/magento sampledata:deploy`

**Describe the results you received:**

Out of memory errors

**Describe the results you expected:**

Sample data is successfully installed

**Additional information you deem important (e.g. issue happens only occasionally):**

I cannot find where to change the value for PHP's `memory_limit` so that it actually "sticks". I have tried adjusting it in the following places:

* /opt/bitnami/php/conf/php.ini
* /opt/bitnami/apache/conf/vhosts/htaccess/magento-htaccess.conf
* /opt/bitnami/magento/htdocs/.user.ini

After changing the values above and restarting the container, the error persists. Also, if I try to install an extension via the admin panel, at the readiness check the memory is always read at 768MB.

http://127.0.0.1/setup/#/readiness-check-updaterreadiness-check-updater/progress

```
Your current PHP memory limit is 768M. We recommend it to be set to 2G or more to use Setup Wizard. As a user with root privileges, edit your php.ini file to increase memory_limit. (The command php --ini tells you where it is located.) After that, restart your web server and try again.
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 6
  Running: 3
  Paused: 0
  Stopped: 3
 Images: 8
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 6.064GiB
 Name: docker-desktop
 ID: NJTM:5WFU:VTOA:I67C:7BQS:E3I3:TGSU:DVIO:C2EO:RKGA:RG53:E5ET
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 76
  Goroutines: 98
  System Time: 2019-08-12T15:39:09.8028854Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2q  20 Nov 2018
```

**Comment by crfroehlich** [comment] 2019-08-12 20:23
Here is my current solution to get around this problem and correctly install the sample data and fix the subsequent permissions issues so that extensions can then be installed from the store.

To get a fully functioning Magento environment (with sample data):

* `$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml > docker-compose.yml`
* `$ docker-compose up -d`
* Fix the PHP memory_limit (change from 768MB/768M to -1) in the following files:
  * `/opt/bitnami/php/conf/php.ini`
  * `/root/.nami/components/com.bitnami.magento/main.js`
  * `/opt/bitnami/apache/conf/vhosts/htaccess/magento-htaccess.conf`
  * `/opt/bitnami/magento/htdocs/.user.ini`
* Add environment variable: COMPOSER_MEMORY_LIMIT = -1
* Restart container
* Verify current memory limit
  * `$ docker exec -it containers_magento_1 /bin/bash` 
  * `$ php -r "echo ini_get('memory_limit').PHP_EOL;"`
* Configure the Magento Marketplace
  * Login to Magento Marketplace: https://marketplace.magento.com/customer/accessKeys/
  * Copy the public/private keys
  * Open the Admin UI: http://127.0.0.1/admin
  * Click System > Web Setup Wizard (http://127.0.0.1/setup/#/home)
  * Click Extension Manager
  * Enter the public/private key to link the Bitnami install with the Marketplace
* Import sample data
  * `$ docker exec -it containers_magento_1 /bin/bash`
  * `$ php /opt/bitnami/magento/htdocs/bin/magento sampledata:deploy`
  * `$ php /opt/bitnami/magento/htdocs/bin/magento setup:upgrade`
  * `$ chown -R bitnami:daemon /opt/bitnami/magento/htdocs`
    * NOTE: sometimes the permissions can be corrupted, because the `daemon` user is no longer part of the `bitnami` group. If this occurs, you can fix the `daemon` user so:
    * Verify the incorrect?, current group assignment: `$ id daemon`
    * Add the `daemon` user to the `bitnami` group: `$ usermod -G bitnami daemon -a`
    * Verify the correct, current group assignment: `$ id daemon`
    * Restart container

**Comment by juan131** [comment] 2019-08-13 07:32
Hi @crfroehlich 

Thanks so much for sharing such a detailed guide to insta the sample data!! We really appreciate you shared it with the rest of the community.

Regarding your issue to configure the PHP memory_limit. Do you think it could be use to include a new environment variables (sth like: **MAGENTO_PHP_MEMORY_LIMIT**) that allows to configure the setting easily?

**Comment by crfroehlich** [comment] 2019-08-13 13:15
A `MAGENTO_PHP_MEMORY_LIMIT` environment variable would be fantastic! There seem to be a lot of issues running Magento with less than 2GB of memory for PHP, so it might be worth pointing that out in the docs and making the default 2GB as well? Regardless, if it can be set in one place with an env var, that solves the problem neatly.

**Comment by juan131** [comment] 2019-08-13 15:56
Hi @crfroehlich 

I just created a task to work on adding this new environment variable to the container. Thanks so much for your feedback.

We'll keep you updated about our progress.

**Comment by carrodher** [comment] 2019-08-29 06:26
Hi, I marked this case as `on-hold` to avoid _stale-bot_ closing it.
We still have this task included in our backlog. As the impact of the issue is not critical, there are no immediate plans to work on it. Nevertheless, it will be considered for future application versions.

We will update this thread as soon as we have more news.

**Comment by lblabr** [comment] 2019-11-13 07:29
> Here is my current solution to get around this problem and correctly install the sample data and fix the subsequent permissions issues so that extensions can then be installed from the store.
> 
> To get a fully functioning Magento environment (with sample data):
> 
> * Install the containers
>   
>   * `$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-magento/master/docker-compose.yml > docker-compose.yml`
>   * `$ docker-compose up -d`
> * Fix the PHP `memory_limit`
>   
>   * Fix the PHP memory_limit (change from 768MB/768M to -1) in the following files:
>     
>     * `/opt/bitnami/php/conf/php.ini`
>     * `/root/.nami/components/com.bitnami.magento/main.js`
>     * `/opt/bitnami/apache/conf/vhosts/htaccess/magento-htaccess.conf`
>     * `/opt/bitnami/magento/htdocs/.user.ini`
>   * Add environment variable: COMPOSER_MEMORY_LIMIT = -1
>   * Restart container
>   * Verify current memory limit
>     
>     * `$ docker exec -it containers_magento_1 /bin/bash`
>     * `$ php -r "echo ini_get('memory_limit').PHP_EOL;"`
> * Configure the Magento Marketplace
>   
>   * Login to Magento Marketplace: https://marketplace.magento.com/customer/accessKeys/
>   * Copy the public/private keys
>   * Open the Admin UI: http://127.0.0.1/admin
>   * Click System > Web Setup Wizard (http://127.0.0.1/setup/#/home)
>   * Click Extension Manager
>   * Enter the public/private key to link the Bitnami install with the Marketplace
> * Import sample data
>   
>   * `$ docker exec -it containers_magento_1 /bin/bash`
>   * `$ php /opt/bitnami/magento/htdocs/bin/magento sampledata:deploy`
>   * `$ php /opt/bitnami/magento/htdocs/bin/magento setup:upgrade`
>   * `$ chown -R bitnami:daemon /opt/bitnami/magento/htdocs`
>     
>     * NOTE: sometimes the permissions can be corrupted, because the `daemon` user is no longer part of the `bitnami` group. If this occurs, you can fix the `daemon` user so:
>       
>       * Verify the incorrect?, current group assignment: `$ id daemon`
>       * Add the `daemon` user to the `bitnami` group: `$ usermod -G bitnami daemon -a`
>       * Verify the correct, current group assignment: `$ id daemon`
>       * Restart container

i'm new to docker how do i change the files ?

**Comment by lblabr** [comment] 2019-11-13 07:34
how do i persist these changes ?

**Comment by juan131** [comment] 2019-11-13 11:49
Hi @lblabr 

Do you mean the PHP memory limit changes or the whole process?

**Comment by michalmikolajczyk** [comment] 2019-11-26 12:33
how to persist the PHP memory limit changes? I am having a hard time doing that on Kubernetes. There is no persistence on the containers, as they are shuffled every 24H

**Comment by juan131** [comment] 2019-11-26 16:41
Hi @michalmikolajczyk 

The PHP settings aren't persisted so you need a way to automate the process of adapting them during the initialization of the containers. We plan to provide a way to do so via environment variables but we didn't have time to work on the associated task yet.

In the meantime, I guess you need to look for other alternatives, such as using initContainer(s) to adapt them before starting the Magento container.

**Comment by michalmikolajczyk** [comment] 2019-11-27 21:20
I guess I need to substitute the files? That's a bit cumbersome :/

**Comment by juan131** [comment] 2019-11-28 08:59
I agree @michalmikolajczyk 
Hopefully we can find some time to address the associated task and we can provide a good solution.

**Comment by michalmikolajczyk** [comment] 2020-02-05 13:12
Any updates perhaps?

**Comment by juan131** [comment] 2020-02-06 08:12
Hi @michalmikolajczyk 

We did not have time to implement this feature yet. 

We plan to extend this solution to all the PHP solutions (not only Magento) so **memory_limit** and other basic PHP settings are easy to modify via environment variables.

**Comment by michalmikolajczyk** [comment] 2020-02-06 14:13
hi @juan131 so I started working on this, and I am experiencing some problems, perhaps you would know what is going on?

What I did:

1. created a new volume and mounted it at `/magentoscript`

2. execced into the container created a script at `/magentoscript/memory-setup.sh`
```bash
#!/bin/bash

sed -i 's/128M/-1/g' /opt/bitnami/php/conf/php.ini
sed -i 's/768M/-1/g' /opt/bitnami/php/conf/php.ini
sed -i 's/768M/-1/g' /root/.nami/components/com.bitnami.magento/main.js
sed -i 's/756M/-1/g' /opt/bitnami/apache/conf/vhosts/htaccess/magento-htaccess.conf
sed -i 's/756M/-1/g' /opt/bitnami/magento/htdocs/.user.ini
```

(please notice some values were 756M)

3. granted execution rights to the script `chmod u+x /magentoscript/memory-setup.sh`

4. added the env var `COMPOSER_MEMORY_LIMIT` with value `-1` into container definition

5. added these properties into container definition:

```YAML
command: ["/bin/bash", "-c"]
args: ["/magentoscript/memory-setup.sh ; /app-entrypoint.sh ; /run.sh"]
```

which should basically run my script before the other scripts.

---

The result:

upon restart, the file `/opt/bitnami/apache/conf/vhosts/htaccess/magento-htaccess.conf` is missing. Also the directory `/vhosts` is not present. The container is restarted then gets into CrashLoopBackoff.

**Comment by g00ntar** [comment] 2020-02-06 20:42
@michalmikolajczyk 
I think you shold use `/docker-entrypoint-init.d` for more info look at https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-10/rootfs/post-init.sh

**Comment by michalmikolajczyk** [comment] 2020-02-06 21:30
@g00ntar why do you think that setting the memory should happen in the `post-init.sh` script?

**Comment by juan131** [comment] 2020-02-07 07:30
Hi @michalmikolajczyk 

You're basically replacing the original command/entrypoint by doing this:

```
command: ["/bin/bash", "-c"]
args: ["/magentoscript/memory-setup.sh ; /app-entrypoint.sh ; /run.sh"]
```

Instead of doing so, you need add your customizations at `post-ini.sh` file (see https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-9/rootfs/post-init.sh) withou modifying the command/entrypoint.

You need to do it at that point since PHP hasn't been initialized until this point:  https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-9/rootfs/app-entrypoint.sh#L11

Please note that Magento won't be started until the `run.sh` (see https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-9/rootfs/run.sh) is executed which will happen after the `post-init.sh`

**Comment by michalmikolajczyk** [comment] 2020-02-07 15:55
well, it kind of worked. I had to manually delete the file `/bitnami/"$BITNAMI_APP_NAME"/.user_scripts_initialized` every time I wanted the scripts to run on the next startup. So now when I remove that file, PHP memory settings seems to be unlimited.

**Comment by juan131** [comment] 2020-02-10 08:53
Hi @michalmikolajczyk 

Why did you need to do so? Why not adding your custom code outside the "if" statement below:

- https://github.com/bitnami/bitnami-docker-magento/blob/master/2/debian-9/rootfs/post-init.sh#L5

This way you can execute them on every run, even though there are other scripts that are meant to be run just once.

**Comment by michalmikolajczyk** [comment] 2020-02-10 11:06
@juan131 do you mean to make my own copy of `post-init.sh` and mount it? It's no use to modify the script in the container - it has no persistent storage (actually the node is recycled every 24h)

Perhaps we could add a rule to that file, so it processes scripts from another directory every time?

**Comment by juan131** [comment] 2020-02-12 09:08
Sorry I closed the issue by mistake!

> Do you mean to make my own copy of **post-init.sh** and mount it? It's no use to modify the script in the container?

Yes, I was talking about creating your "own Magento container" based on this one.

**Comment by miguelaeh** [comment] 2020-04-08 08:03
Hi,
I would like to notify you that we just released a version that contains the env var `PHP_MEMORY_LIMIT` to allow you to modify the PHP memory limit.
You can find more information here: https://github.com/bitnami/bitnami-docker-magento/#php-configuration
Could you give it a try?

**Comment by gibkigonzo** [comment] 2020-10-26 14:15
@miguelaeh I had same problem and I can confirm that increased `PHP_MEMORY_LIMIT` solved it. Thank you!

**Closed** 2020-10-26 14:45 UTC
Labels: on-hold
